# Generated by Django 3.1.4 on 2021-01-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
